version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: strapi-utils
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-provider-upload-cloudinary
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-plugin-content-manager
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-connector-bookshelf
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-plugin-upload
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-admin
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: "@ckeditor/ckeditor5-react"
    versions:
    - 3.0.0
    - 3.0.1
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
  - dependency-name: urijs
    versions:
    - 1.19.5
